### ISSUE TITLE
Client freeze when looking at Mekanism machines and cables

### ISSUE THREAD

**Issue by dcorallo** [benbenlaw/seaopolis#101]
Just want to make you aware of this bug: https://github.com/mekanism/Mekanism/issues/7195
Unfortunately the freeze (and sometimes crash) is not 100% reproduceable. 
Another user on my server had this issue from the first day. While I started freezing/crashing about a week later. 
Some cables and machines never produce this bug, but some will always freeze the client. 
Disabling TOP "fixes" the issue, but I'm feeling kind of blind without it.

**Comment by Vikbor5342** [comment]
I believe the mod was remvoed in newer versions of the modpack. What version are you playing on?

**Comment by benbenlaw** [comment]
this has been fixed in newer versions of the pack
