### ISSUE TITLE
Death Becon not going away

### ISSUE THREAD

**Issue by Dragoid22** [benbenlaw/seaopolis#104]
**Describe the bug**
after dying there is a waypoint that is created after I remove it in journey there is still a white beam that you cant get rid of
**To Reproduce**
1. die
2. clear journey waypoint
3. walk away from point of death

**Expected behavior**
not to sure need a way to remove the 

beam

**Screenshots**
![2021-07-12_14 18 35](https://user-images.githubusercontent.com/75586509/125344097-7c5d2280-e31c-11eb-8372-a415387bc019.png)
**Version**
1.5

**Additional context**

**Comment by LotP1** [comment]
this has been fixed in 2.0
to remove already existing beacons press "m" to open the ftb chunks map and delete the death markers

**Comment by Dragoid22** [comment]
thank you that worked
