### ISSUE TITLE
Seabucks Missing

### ISSUE THREAD

**Issue by Elibikerdude** [benbenlaw/seaopolis#109]
Me and my friend tried to play a server on seaopolis and the seabucks arent there

![image](https://user-images.githubusercontent.com/29840475/126085482-55a2b518-df2f-46f5-b1db-066497b8d2c2.png)

**Comment by benbenlaw** [comment]
this is becuase you didnt install the server using thje server files, you must have the kubejs folder in there as well

**Comment by Elibikerdude** [comment]
Alright thanks for the help
