### ISSUE TITLE
I have 1 fps

### ISSUE THREAD

**Issue by GameHost01** [benbenlaw/seaopolis#112]
So, when i load into a world i have 1-2 fps, I already tried reinstalling Minecraft, Java, the modpack but nothing helped.
Here is the log and screenshots:
[latest.log](https://github.com/benbenlaw/seaopolis/files/6872336/latest.log)
![2021-07-24_13 46 18](https://user-images.githubusercontent.com/53171814/126867442-bf65ac02-0f31-42a0-975c-c01969b868a8.png)
![2021-07-24_13 30 46](https://user-images.githubusercontent.com/53171814/126867265-4a1e2a4d-2a76-4a1e-8e7e-af5de40c32ee.png)
![2021-07-24_13 30 52](https://user-images.githubusercontent.com/53171814/126867207-665025ff-5617-4daf-b78c-34cbb3e52575.png)

**Comment by Vikbor5342** [comment]
Please join the discord. https://discord.gg/aKgDH99hBu

**Comment by GameHost01** [comment]
> 
> 
> Please join the discord. https://discord.gg/aKgDH99hBu

I have, what should i do?
