### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by TeaKettleWasTaken** [benbenlaw/seaopolis#114]
My game crashes every time I enter a world for the second time.

To do it create a world Exit Minecraft and then try to join back

Maybe not for everyone but it gives Java not Responding and error code 0.

Version
Seaopolis 4.0
Minecraft 1.16.5

I have the newest java and have tried jarfix I have the specs to run the game its runs perfectly when first joining but the second times the problem. I'm using the curse forge app.

CrashLog: (hopefully this is the right thing)
Log Name: Application
Source: Application Hang
Event ID: 1002
Level: Error 
User: N/A
OpCode: Info
Logged: 7/24/2021 12:44:57 PM
Task Category: (101)
Keywords: Classic
Computer: DESKTOP-N7RL26O

**Comment by LotP1** [comment]
please include the crashlog

**Comment by TeaKettleWasTaken** [comment]
> please include the crashlog

just updated it it hope its the right thing if not I might need help I'm newer to computers

**Comment by LotP1** [comment]
ah, that's the wrong file
open curseforge and r-click the seaopolis profile and open folder. there you should see a folder called crashlogs, find the newest file in there and upload it here

**Comment by TeaKettleWasTaken** [comment]
[crash-2021-07-24_13.34.25-server.txt](https://github.com/benbenlaw/seaopolis/files/6872939/crash-2021-07-24_13.34.25-server.txt)
 This it?

**Comment by LotP1** [comment]
yes, give me a min to find the problem

**Comment by LotP1** [comment]
ah, it seems like the modpack didn't install correctly.
please try reinstalling :)

**Comment by TeaKettleWasTaken** [comment]
ok thanks will it keep my world?

**Comment by LotP1** [comment]
to save your world do this:
copy your world folder to a safe location, then copy it back into the new profile and lastly delete the folder called "server-configs" inside the world folder

**Comment by TeaKettleWasTaken** [comment]
thanks you I love your projects and something I need to add is that people can cheat sandstone early by going into the skeleton mouth and getting sand I cant wait for infernopolis have a great day

**Comment by TeaKettleWasTaken** [comment]
thank you it seems to be working

**Comment by LotP1** [comment]
ye, that's a known skip, but it's really early game and can be seen as a reward for exploring ;)

**Comment by TeaKettleWasTaken** [comment]
yeah

**Comment by TeaKettleWasTaken** [comment]
Its acting up again here's the crash report
[crash-2021-07-25_14.02.43-server.txt](https://github.com/benbenlaw/seaopolis/files/6874440/crash-2021-07-25_14.02.43-server.txt)

**Comment by LotP1** [comment]
go into your world folder and delete the "serverconfig" folder

**Comment by TeaKettleWasTaken** [comment]
this is a new world because of how I didn't understand how to change the worlds and its a lot better

**Comment by TeaKettleWasTaken** [comment]
its also updated to 4.2

**Comment by LotP1** [comment]
go into curseforge
click on the seaopolis profile
click the 3 dots next to the play button
choose "open folder"
go into saves to find your worlds
in your world's folder you delete the folder called "serverconfig"

**Comment by TeaKettleWasTaken** [comment]
done

**Comment by LotP1** [comment]
now try to join the world again

**Comment by TeaKettleWasTaken** [comment]
ok

**Comment by TeaKettleWasTaken** [comment]
immediate not responding

**Comment by LotP1** [comment]
give it some time
also allocate som more ram to the pack
we recommend 6-8 gb

**Comment by TeaKettleWasTaken** [comment]
ok

**Comment by TeaKettleWasTaken** [comment]
gave it 7 doesn't work at all

**Comment by TeaKettleWasTaken** [comment]
idk if i need a better computer or not

**Comment by LotP1** [comment]
you deleted the folder called "serverconfig" right? not the ones called "configs" or "default configs", without those 2 the game won't work

**Comment by TeaKettleWasTaken** [comment]
yes

**Comment by LotP1** [comment]
how much ram does your pc have?

**Comment by LotP1** [comment]
also this is getting too long for a github issue
please join the discord server

**Comment by TeaKettleWasTaken** [comment]
its 8 but I tried giving Minecraft 4 5 And 7 gigs also none worked

**Comment by TeaKettleWasTaken** [comment]
original gigs were 2

**Comment by TeaKettleWasTaken** [comment]
(for minecraft)

**Comment by TeaKettleWasTaken** [comment]
here's the newest crash report don't know if it will help
[crash-2021-07-25_15.01.53-server.txt](https://github.com/benbenlaw/seaopolis/files/6874481/crash-2021-07-25_15.01.53-server.txt)

**Comment by TeaKettleWasTaken** [comment]
oh just saw the message
