### ISSUE TITLE
Mystical Agriculture Seed Issue

### ISSUE THREAD

**Issue by AdideezGames** [benbenlaw/seaopolis#115]
I'm not getting any extra seeds after harvesting Inferium Seeds, I started out with 8 seeds, let it run all night and when I got back on, I still had 8 seeds. I tried restarting my game and that didn't work. pls help

Extra Note, my game did get corrupted and I'm playing on a backup of a world, maybe that will help with the issue.

**Comment by ValkyrieViolet** [comment]
Are you using normal farmland? You need to use any mystical farmland for more inferium seeds

**Comment by AdideezGames** [comment]
It Worked! Thanks a lot bro I have been trying to figure it out for a couple hours now, and never thought to use the mystical farmland.
