### ISSUE TITLE
BUG Severing V and luckiest cleaver is not dropping as many heads as it should

### ISSUE THREAD

**Issue by jinkhya** [benbenlaw/seaopolis#116]
**Describe the bug**
Hello, 
Something is wrong with wither skeleton head drops using tinker. A cleaver with Severing V and luckiest should drop heads at least one out of two kills. To compare, I made an instance with just tinkers and with the same cleaver stats I get lots of heads, on Seaopolis it took me 30 kills to get one. 

**To Reproduce**
1. Make a cleaver with Severing V and luckiest (material used for the cleaver is irrelevant)
2. kill wither skeletons and see how long it takes to get one head.
3. Optional: compare the drops in an instance with just tinkers

**Expected behavior**
To get more wither skeleton heads.
According to an admin in tinker's discord, drop rate should be about 35% for just Severing V and 70% when coupled with luckiest.

**Screenshots**

**Version**
0.4.2

**Comment by LotP1** [comment]
this is a problem with tinkers construct
please report it to the mod devs

**Comment by jinkhya** [comment]
It isn't though I tried same version as seaopolis (171) with no other mods and it works fine

**Comment by LotP1** [comment]
huh, i'll report it to Ben on the discord server

**Comment by benbenlaw** [comment]
i think its fixed with latest tinkers update if not i will reopen
