### ISSUE TITLE
Multiservo Press recipe for lead gear using silver ingots in version 5.0

### ISSUE THREAD

**Issue by guykv** [benbenlaw/seaopolis#119]
**Describe the bug**
Issue title should suffice.

**To Reproduce**
1. Open JEI
2. Search for 'Lead Gear'
3. Point to the lead gear, press 'R'
4. Select the Multiservo Press tab

**Expected behavior**
The recipe should require 4 lead ingots as input to the machine.

**Screenshots**
![image](https://user-images.githubusercontent.com/3527671/127626021-6a943f9c-4fc3-4557-975a-ab48a8235cba.png)

**Version**
5.0

**Additional context**
N/A

**Comment by benbenlaw** [comment]
update going up right now that fixes this
