### ISSUE TITLE
Mekanism x5 ore processing converts Dirty Lead Dust to Silver Dust instead of Lead Dust

### ISSUE THREAD

**Issue by recanem** [benbenlaw/seaopolis#120]
Mekanism x5 ore processing converts Dirty Lead Dust to Silver Dust instead of Lead Dust.  Should likely convert Dirty Lead Dust to Lead Dust.  Seaopolis 5.0 release. If additional information would be helpful please let me know.

**Comment by benbenlaw** [comment]
fixed in 5.1
