### ISSUE TITLE
pyrolizer quest not opening

### ISSUE THREAD

**Issue by destroina** [benbenlaw/seaopolis#121]
after crafting the pyrolyzer the quest still not opening

in the industrial foregoing quest
i try to do the plastic quest
got the latex, went for the fractionating still and got the rubber and its reward, after that not possible to move on

it should unlock the pyrolyzer and get its reward

![seaopolis bug](https://user-images.githubusercontent.com/49697949/127934358-5bdffe53-75d9-4eb0-ab1d-44f15086ffdf.PNG)

version 5.3

i play on a server

**Comment by midnightodyssey** [comment]
pyrolyzer quest requires both the rubber quest and netherrack quests. You can use the arrow in the top left of a quest to check what its dependencies are.
![image](https://user-images.githubusercontent.com/88525785/128458043-bfdafc0a-f652-449e-9eb0-1e0c4f8ae4ed.png)

**Comment by destroina** [comment]
nice, thanks, never noticed that
