### ISSUE TITLE
Cant Make Iron Plate To Advance On The Modpack

### ISSUE THREAD

**Issue by anderson-bap** [benbenlaw/seaopolis#122]
**Describe the bug**
When i was trying to start the machine creation part of the mod i realized that i could not make the iron plates even having every thing i needed to make it because the tinker's furnace wont give me the correct item.

**To Reproduce**
1. Go to a tinker's furnace.
2. Put iron on it.
3. Try to make iron plate.
4. Fail because the game gave u the wrong item.

**Screenshots**
![image](https://user-images.githubusercontent.com/88352914/127934646-f94d97a7-1c9c-445e-8cba-cadbdeefd70a.png)

**Version**
5.0

**Comment by anderson-bap** [comment]
i tryed to update the modpack to 5.3 to see if the furnace work and my world became corrupted.

**Comment by LotP1** [comment]
please send a crashlog for the corrupted world
the original issue was solved in 5.3

**Comment by anderson-bap** [comment]
[crash-2021-08-02_20.41.35-server.txt](https://github.com/benbenlaw/seaopolis/files/6920199/crash-2021-08-02_20.41.35-server.txt)
[crash-2021-08-02_20.47.58-server.txt](https://github.com/benbenlaw/seaopolis/files/6920200/crash-2021-08-02_20.47.58-server.txt)
while trying to get the world back i tryed to open it in vanilla mode soo i will send the 2 more recent crash txt

**Comment by LotP1** [comment]
do not open modded worlds in vanilla
that will break the world
and i see an old beta bug is back, if you send me the region file called r.0.0.mca i can fix the original coruption for you

**Comment by anderson-bap** [comment]
Where to i find that file

**Comment by LotP1** [comment]
in the region folder in your world folder

**Comment by anderson-bap** [comment]
I think the map is lost because theres nothing in the region file, is there any chance its because i opened it in vanilla mode?

**Comment by anderson-bap** [comment]
i tryed to open my backup map (the one that the modpack creates every some time) and it didnt corrupted when i tryed to open inn 5.3, is there a chance  that it was because of i loaded nether chuncks in the old map or the iron plate thing?

**Comment by LotP1** [comment]
no, it's not empty, it's just s special file type
and yes, opening in vanilla has probably broken the world

**Comment by anderson-bap** [comment]
oh... thats why

**Comment by LotP1** [comment]
no, it was a loading glitch with the wooden crucible
and nice the backup worked

**Comment by anderson-bap** [comment]
oh... wooden crucible is soo powerfull, and just askin is there any command to force the backup thing?

**Comment by anderson-bap** [comment]
thx for help btw, u helped me a lot.

**Comment by LotP1** [comment]
i don't remember if there's a way to force backup
but it will automatically back up every 2 hours

**Comment by anderson-bap** [comment]
oh ok
