### ISSUE TITLE
Blaze bucket quest bugged

### ISSUE THREAD

**Issue by Mullegil** [benbenlaw/seaopolis#124]
The quest for obtaining a molten blaze bucket is bugged.  The only molten blaze that exists is blazing blood, but it doesn't register for the quest. This also means you can't obtain Vitamins since this quest is a prerequisite.

![blaze](https://user-images.githubusercontent.com/88585093/128601552-13139bf6-2d85-45dc-bc4b-7a46f1eab22a.png)

**Comment by benbenlaw** [comment]
thanks fixed in dev
