### ISSUE TITLE
Fired Crucile melting but not giving any lava

### ISSUE THREAD

**Issue by PandarenArcher** [benbenlaw/seaopolis#127]
**Describe the bug**
I have my crucible over a heat soource and when i put any crushed material in it melts all the way down but doesnt leave any lava in crucible. The crucible is just empty
Edit: Just noticed the lava is going into the crucible but its just not showing. Crucible appears empty but lava is in it. Possible visual bug

**Version**
6.0

**Additional context**

**Comment by benbenlaw** [comment]
are you using optifine
