### ISSUE TITLE
在添加optfine之后无法正常打开存档

### ISSUE THREAD

**Issue by ZCLDAYEDE** [benbenlaw/seaopolis#128]
这是相关的错误报告
[错误报告-2021-8-18_23.21.06.zip](https://github.com/benbenlaw/seaopolis/files/7011560/-2021-8-18_23.21.06.zip)

**Comment by moody69420** [comment]
卸载优化

**Comment by ZCLDAYEDE** [comment]
能否在不关闭optfine的情况下解决相关问题呢？

**Comment by LotP1** [comment]
optifine is not supported

**Comment by ZCLDAYEDE** [comment]
okey～
