### ISSUE TITLE
Valkyrie lib unnecessary (possibly)

### ISSUE THREAD

**Issue by wcdanh2** [benbenlaw/seaopolis#13]
https://www.curseforge.com/minecraft/mc-mods/valkyrielib

ValkyrieLib is included in the pack, but does not appear to have any mods that rely on it included in the pack.

**Comment by benbenlaw** [comment]
advanced rocketry

**Comment by wcdanh2** [comment]
Interesting, I don't see it listed as a requirement. I'll do more research.

**Comment by wcdanh2** [comment]
The advanced rocketry page specifies it needs libVulpes but I do not see any reference to valkyrielib.

If removed:
Loading the game and selecting an existing world the logs will show valkyrie lib as missing but the game otherwise appears to load normally. If I create a new world the logs do not mention valkyrielib.

Does leaving it in cause any issues: Minor game start time increase.  Unless there is something that will only trigger if a mod block from advanced rocketry actually needs it.  In which case it would be a bug to report to the advanced rocketry authors.

Does taking it out cause any issues:  As far as I can tell only a minor warning on the log files. If you are loading a world that was created with valkyrielib installed.
