### ISSUE TITLE
Can't buy certain items from shop

### ISSUE THREAD

**Issue by CrashGamer75** [benbenlaw/seaopolis#130]
I am unable to buy ender pearls even though I have enough for them. There are many other examples that is just one.

If you go to shop and see some things are darker that means you can't buy them; that's what's happening to me even though i have well over enough to buy them. The Seabucks are in my hotbar but I still cannot purchase Them

I really wanted the Ender Pearls to make elevaters, which would have made easy access between top and bottom

**Comment by moody69420** [comment]
you need to unlock them first check top left arrow on what to do to unlock it

**Comment by CrashGamer75** [comment]
yea i realized that lol
