### ISSUE TITLE
Cannot get iron plates

### ISSUE THREAD

**Issue by VesperHarp** [benbenlaw/seaopolis#131]
Hello, I cannot get Iron plates as the small plate cast doesn't have any associated recipes and other ways require machines.

I am playing on version 7.1.

Thanks for your help

![image](https://user-images.githubusercontent.com/90214691/132252542-a2175bb8-dc5f-479f-8983-caa14115736b.png)

**Comment by benbenlaw** [comment]
Update to 7.2
