### ISSUE TITLE
Hard to Describe

### ISSUE THREAD

**Issue by CrashGamer75** [benbenlaw/seaopolis#135]
So the bug is that when I get an item ahead in the questline, it becomes blue, then when I actually get to it a cannot progress beyond that.

For example, I got prosparity shards a while ago, i just now started the mystical agriculture quests but even though I have the infusion altar it does not complete the quest, same with everything beyond the blue circled item. 

I have put a prosparity shard in my inventory to see if it would complete it. It did not. But I have realized that it coounts the blue circled item as completed, but also not completed, because it says 100% completed even though when you pin it it says 0%, also you cannot claim the seabuck, so I am unable to progress in the questline.

**Comment by LotP1** [comment]
this problem requires an admin to reset your quest progression on that specific quest
this should not be a problem in the newest version, but any quests that are already soft-locked will still require fixing

**Comment by CrashGamer75** [comment]
Thank you but I have one major problem, I am playing on a single player server. So how can I reset the progress???

**Comment by moody69420** [comment]
./ftbteams party create

**Comment by LotP1** [comment]
join the discord server and check the faq

**Comment by CrashGamer75** [comment]
Thank You!!!
