### ISSUE TITLE
Scuba-Mask BUG

### ISSUE THREAD

**Issue by Astr0o** [benbenlaw/seaopolis#136]
I'm stuck in missions because of the scuba mask one. I crafted the Mask, it was pretty hard, and it didn't complete for me.
Now I'm continuing the missions without completing anything. You should have a "Submit" Button for every quest, not only for those which have multiple objectives.

**Comment by benbenlaw** [comment]
version?

**Comment by LotP1** [comment]
did you complete all the required quests before the scuba helmet one?
please send a screenshot of the quest

**Comment by CrashGamer75** [comment]
probably was a ftb quests bug. you could edit and make the scuba mask quest complete
