### ISSUE TITLE
No Blaze recepie even thoe it says there is in the book.

### ISSUE THREAD

**Issue by Boncuk1905** [benbenlaw/seaopolis#14]

**Comment by wcdanh2** [comment]
Adding Info:
In the tab "thermal Expansion" chapter "machines" the quest "Blaze Rod" the description states that a blaze rod can be crafted in a "press server" (possibly a typo that meant "multiservo press" which is the item crafted in the previous quest).  However JEI does not show that a blaze rod can be crafted in a multiservo press directly.  It appears that the intent is for the user to use the multiservo press to create molten blaze and then use a casting table to craft the rod.

The quest could instead say: "Blaze rods can be made using molten blaze from the multiservo press and a casting table"

**Comment by benbenlaw** [comment]
this is a bug blaze rods need the smeltery now
