### ISSUE TITLE
'checkerboard' Grass Block Texture when using Sieve.

### ISSUE THREAD

**Issue by SauceOfficial** [benbenlaw/seaopolis#140]
![image](https://user-images.githubusercontent.com/71516797/133886097-46af991f-8b7b-4763-9ede-a57598975d4e.png)

**Comment by LotP1** [comment]
mod issue
we're still waiting on a fix

**Comment by SauceOfficial** [comment]
> mod issue
> we're still waiting on a fix

i was expecting that answer

**Comment by benbenlaw** [comment]
#28
