### ISSUE TITLE
Custom Cobble Generator Configs for Servers are incorrect.

### ISSUE THREAD

**Issue by voxpop9** [benbenlaw/seaopolis#141]
When I installed the server, it had incorrect custom cobble gen configs and did not have the client mod gens.

Temporary fix: Copy client Seaopolis config files to Server config files

**Comment by LotP1** [comment]
i'm 99% sure your server just had a bad install, i've only ever seen this issue once before, and a reinstall of the server fixed it

**Comment by voxpop9** [comment]
I see. Still got it fixed by copying the config files over regardless. Should I close the bug report or leave it up?

**Comment by LotP1** [comment]
just close it :)
