### ISSUE TITLE
Blast chiller molten metal to ingot consumes tinkers cast

### ISSUE THREAD

**Issue by NyanHype** [benbenlaw/seaopolis#142]
![Screenshot_1](https://user-images.githubusercontent.com/36115380/134813278-16e9ec58-d9a1-44e4-85b4-93684b8da8d4.png)

Recipes with the tinkers cast like the second one consume the tinkers cast, but the ones with the thermal cast like the first one don't consume the cast, i believe all the ingot recipes should not consume the cast to allow ore processing to occur from sieve > smeltery > blast chiller, instead of using casting tables or casting basins

**Comment by benbenlaw** [comment]
thanks fixed in 14.0
