### ISSUE TITLE
Visual overlay not being removed

### ISSUE THREAD

**Issue by Gyohwalhan** [benbenlaw/seaopolis#143]
**Describe the bug**

When playing, some items will display on the right middle of the screen a visual representation of their % usage (even if it is not an item that gets used up). See the attached screenshot. Restarting the game does not fix the issue. Please note the error persists regardless of in-game actions including item usage, death, and interactions. 

**To Reproduce**
It is unclear what caused the issue or how to recreate it. The bait pot was the first item to show up and the grout was after it. 

**Screenshots**
![image](https://user-images.githubusercontent.com/91434306/134822227-2e0b6c11-1b65-417d-b69a-a05aa462daf8.png)
![image](https://user-images.githubusercontent.com/91434306/134822241-a9fc2f4b-49c8-441e-ba61-d867a47fd4b0.png)

**Version**
Current version

**Comment by DiGGyRoCk** [comment]
That looks like Pinned Quests. Go into the representing quest and click the pin to turn it off...

**Comment by Gyohwalhan** [comment]
Thank you... I was convinced that was a bug. Still new to mods. Thanks again for the help!
