### ISSUE TITLE
Infinite Seabuck Glitch

### ISSUE THREAD

**Issue by alakes** [benbenlaw/seaopolis#145]
**Describe the bug**
Using "/ftbteams party create" and "/ftbteams party leave", I am able to claim and reclaim Seabuck infinitely

**To Reproduce**
1. Type "/ftbteams party create"
2. Obtain a log to complete the 1st quest
3. Claim Seabuck
4. Type "/ftbteams party leave"
5. Repeat 1. step

**Expected behavior**
The quest remember the quest I have done even if I leave or create again.

**Version**
Minecraft version 1.16.5
Seaopolis version 10.1
Singleplayer

**Additional context**
Video link shows the steps to produce the glitch *apologize for the low fps*
https://www.youtube.com/watch?v=8kWrPlWvH1Q

**Comment by LotP1** [comment]
tthis is expected behavior
when you use the create command you make a whole new team, which will have new quest progress
if you were expecting to resume your old quest progress, you'd have to join back into the same team you left, which is not what you're doing
