### ISSUE TITLE
loading in of my older world is not working

### ISSUE THREAD

**Issue by AssassinDK123** [benbenlaw/seaopolis#15]
i have gained the issue of trying to load into my world i might guess the reasoning being the bubble made out of clear glass but otherwise i have no clue please do help (and yes my world is named "New World" didnt think i would be so much into it that the test world would be my main world)
[my world.zip](https://github.com/benbenlaw/seaopolis/files/6401746/my.world.zip)

**Comment by wcdanh2** [comment]
I was able to load the world, but it did load slow and there were quite a few items on the ground.  Do you have a log of a failed attempt to load the world?  How much memory do you have allocated to minecraft?

**Comment by wcdanh2** [comment]
[AssassinDK.zip](https://github.com/benbenlaw/seaopolis/files/6402665/AssassinDK.zip)
I was able to load in and set your block breakers to require redstone mode, as well as pick up the items in the immediate area.

Hopefully that does the trick.
