### ISSUE TITLE
Start server crash

### ISSUE THREAD

**Issue by mistergriff** [benbenlaw/seaopolis#151]
**Describe the bug**
I am not able to restart my server after a shutdown

**To Reproduce**
1. IDK, my server was running since 1 week and i needed to restart the server hardware and since that i am not able to restard it.
2. I checked the attached server log and the problem is when the server try to load the level.dat of the world

**Expected behavior**
The server start

**Screenshots**
[message (1).txt](https://github.com/benbenlaw/seaopolis/files/7858409/message.1.txt)

**Version**
Seaopolis 14.1

**Comment by LotP1** [comment]
update
this issue was fixed in 14.3

**Comment by mistergriff** [comment]
Yes and what about the map ? It is definitely corrupted ?

**Comment by LotP1** [comment]
map should be fine
you might have to delete the "ar datapack" from the world's datapack folder

**Comment by mistergriff** [comment]
Ok thanks i'll try it

**Comment by mistergriff** [comment]
It don't works with the only update, but it works with the update + delete "ar datapack". Thanks !!!
