### ISSUE TITLE
BUG - No recipe for Raw Tin or Raw Copper

### ISSUE THREAD

**Issue by EtoileLion** [benbenlaw/seaopolis#157]
**Describe the bug**
There is no recipe for Raw Tin or Raw copper. The Quest text implies it would either need to be Broken by a Bone Hammer or a Knife.

**To Reproduce**
1. Get Gravel Tin/Copper Ore.
2. Have no use for it.

**Expected behavior**
There should be a use for the Gravel Tin/Copper Ore (Presumably a Bone Hammer recipe)

**Screenshots**

**Version**
B7.0

**Comment by Bebobobo** [comment]
post this in the submerged channel. this seaopolis is the archived pack.
