### ISSUE TITLE
slabs allowing light through 

### ISSUE THREAD

**Issue by rws45619** [benbenlaw/seaopolis#18]
slabs not blocking light , no mention in 1.16 changelogs that it is a vanilla mechanic 

![2021-05-01_05 34 42](https://user-images.githubusercontent.com/83497651/116780088-e2d1e480-aa3f-11eb-8c8d-8e469daea58f.png)
![2021-05-01_05 34 52](https://user-images.githubusercontent.com/83497651/116780090-e36a7b00-aa3f-11eb-9415-43b60b5ac475.png)

**Comment by benbenlaw** [comment]
are you reporting a vanilla bug

**Comment by rws45619** [comment]
this is in the mod pack

**Comment by benbenlaw** [comment]
whats the bug though this is a vanilla feature

**Comment by benbenlaw** [comment]
slabs allow light to come through

**Comment by foxwhite25** [comment]
Its a feature in the newer version , that desgin only work in 1.12

**Comment by rws45619** [comment]
okay thank you i didnt know , i have only played in 1.12.2
