### ISSUE TITLE
Mystical Ag. Seeds

### ISSUE THREAD

**Issue by FeedTheChunk** [benbenlaw/seaopolis#19]
V. B1.4  

1 Air seeds have a quest and are craftable however, the air essence has no use.
2. Aluminum seeds don't appear to be craftable unless aluminum becomes available late game.  The aluminum also appears to have no real uses.  Maybe in Advanced Rocketry later on?

Thanks

**Comment by FeedTheChunk** [comment]
So aluminum is obtainable from the laser drill and it does appear that it is used Advanced Rocketry.  Maybe from planets too, although not there yet. 

It feels a little imbalanced with the seed being a level 2 seed but aluminum doesn't become accessible until much later in the pack.

**Comment by benbenlaw** [comment]
alumiunum has been added to sieving

**Comment by FeedTheChunk** [comment]
New rubber seed recipe in B2.0 not showing in JEI.
![2021-05-02_10 06 25](https://user-images.githubusercontent.com/35508630/116817942-6b2eb300-ab2e-11eb-8d8b-4d6cb6fd8acd.png)

**Comment by FeedTheChunk** [comment]
Same issue with the Aluminum Seeds.

**Comment by benbenlaw** [comment]
reinstall

**Comment by FeedTheChunk** [comment]
Zinc and Silver seeds don't show as well in B2.0.  I will update.  Thx
