### ISSUE TITLE
Vanilla Recipe Book

### ISSUE THREAD

**Issue by FeedTheChunk** [benbenlaw/seaopolis#22]
V B2.0 - If the player upgrades to B2.0 and has the recipe book shown, there is no way of hiding the book.

![2021-05-02_09 56 31](https://user-images.githubusercontent.com/35508630/116817585-b47e0300-ab2c-11eb-8cd4-c183e4fa3cd3.png)

**Comment by benbenlaw** [comment]
find this "seaopolis/kubejs/config/client" change "disableRecipeBook=true" to this "disableRecipeBook=false"
