### ISSUE TITLE
KubeJS Errors

### ISSUE THREAD

**Issue by LazyMan13** [benbenlaw/seaopolis#23]
Version B2.2
Following errors found in log:

[KubeJS Server/]: Error creating recipe botanypots:kjs_6mgizkfbhm8uk1s11jdsffl1u[botanypots:soil]: {"type":"botanypots:soil","input":{"tag":"seaopolis:slimy_dirt"},"display":{"block":"seaopolis:slimy_dirt"},"categories":["slimy"],"growthModifier":0.0}: com.google.gson.JsonParseException: Could not find minecraft:block with ID seaopolis:slimy_dirt

[KubeJS Server/]: Error parsing recipe angelblock:angel_block[minecraft:crafting_shaped]: {"type":"minecraft:crafting_shaped","group":"angel_block","pattern":[" G ","FOF"],"key":{"G":[],"O":{"item":"minecraft:black_wool"},"F":{"item":"minecraft:feather"}},"result":{"item":"angelblock:angel_block"}}: com.google.gson.JsonSyntaxException: Item array cannot be empty, at least one item must be defined

**Comment by benbenlaw** [comment]
does it come out as red text in your client

**Comment by LazyMan13** [comment]
In game, no such error presented. Just crops up in the log as such.

**Comment by benbenlaw** [comment]
yeah thats fine

**Comment by LazyMan13** [comment]
Okay, closing issue then.
