### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by ZyberzTTV** [benbenlaw/seaopolis#26]
When I launch up the mod and try join a world it doesnt work, it says "Reading World Data" at first, then that disappears. and it's just completely empty. I've tried duplicate the mod, updating the release, restart like 134 times.. It doesnt even work if I create a new world. The world creates, but im stuck in loading screen. at 1 point it worked, but i tried on another world than my main, and now it wont work again.. pls helpp....

**Comment by benbenlaw** [comment]
logs, ram, cpu maybe your bottlenecked
