### ISSUE TITLE
TASK 

### ISSUE THREAD

**Issue by original4to4** [benbenlaw/seaopolis#34]
In the chapter "Basic Automation" i make the "configurator" and it was not detected, i leave the world than close the game and finally open the game and enter the world but the same result it was not detected. I also tried to craft the "configurator" another time but again it was useles and the task was not detected. Please help me! Thanks!

**Comment by Vikbor5342** [comment]
I cant replicate this issue. 
Make sure you have done all dependencies by pressing the little arrow left to the text "Tasks"
And make sure that the quest is light gray and not dark gray in the quest as light gray means unlocked and dark gray means locked.
