### ISSUE TITLE
Silver Ore Chunk & Mekanism

### ISSUE THREAD

**Issue by shaded1** [benbenlaw/seaopolis#35]
When enriching silver ore after it's been through the purifying and crushing process, it turns into Silver Dust by Pedestals. This forge:dusts/silver is NOT valid for the smelting factory by Mekanism and therefore will not be smelted. 

Thermal Series silver dust IS valid for the Mekanism smelting factory.

**Comment by shaded1** [comment]
I can use the Mekanism Oredictionificator to translate the Pedestals dust into Thermal Series dust, but that seems like an extra step that should not be necessary.

**Comment by shaded1** [comment]
This is in version B4.5

**Comment by shaded1** [comment]
Same thing happens with Nickel going through the same process gets turned into Pedestals nickel dust, which the smelting factory will not accept.

**Comment by benbenlaw** [comment]
so i know this is a issue for some players in the next update you will be able to convert your pedestals dusts into the correct dusts by crafting them

**Comment by anagram3k** [comment]
This is happening to me too. 
I am using java 1.8.0_281 64-bits on Linux with MultiMC
