### ISSUE TITLE
unable to interact with objects

### ISSUE THREAD

**Issue by SaltiestLemon** [benbenlaw/seaopolis#44]
Occasionally me and my friends have encountered an issue where we are unable to open chests or sleep or break blocks, whilst some other people are able to do so in the same world, nothing has been claimed by FTB Teams.

https://user-images.githubusercontent.com/84578406/119145656-c4a94400-ba41-11eb-8e84-3f763fcbb370.mp4

**Comment by benbenlaw** [comment]
gonna guess that he is a op on the server and your not meaning that for you its spawn protected maybe
