### ISSUE TITLE
Crash loading Seaopolis after updating to Version 5.2

### ISSUE THREAD

**Issue by Ladysarajane** [benbenlaw/seaopolis#45]
Just updated from B5.1 to version 5.2. When running the update first time, my AVG antivirus alerted that Apple skin was malware. I made an exception and the modpack gave me this error:
![Screenshot (10)](https://user-images.githubusercontent.com/34258851/119150640-a1b86900-ba1c-11eb-8829-f32566b1f880.png)

I attempted to reinstall the modpack think files were messed up and again when running it, it came with the above error when running. 

For now I will go back to version B5.1 till this is fixed. 

Oh the crash file:
[crash-2021-05-21_09.40.52-fml.txt](https://github.com/benbenlaw/seaopolis/files/6523102/crash-2021-05-21_09.40.52-fml.txt)

**Comment by LotP1** [comment]
seems like it's an install error on your side as everyone else can install fine
try reinstalling to see if that fixes it

**Comment by Ladysarajane** [comment]
I did install it to a new profile again as I stated. Same error. Overwolf/Curse still not playing nice with downloads. I will give it a couple days till their next update and try again. Hmmm.....I wonder??? Apple skin is listed as a jar file in my mods folder. But the error says Apple skin is not a jar file. I wonder if even though I made an exception in my AVG if it is preventing it from downloading correctly?

**Comment by LotP1** [comment]
i'm 99% sure that's it

**Comment by Ladysarajane** [comment]
That was it...AVG is changing it even though I made an exception for it. I have it corrected now. Not sure why the new definitions of AVG have decided to alert on those. I have the issue solved now. It was the same file as on B5.1, so I deleted the bad file and copied the old file to the new profile.
