### ISSUE TITLE
Akashic Tome interacts oddly with some modded books.

### ISSUE THREAD

**Issue by calliereimann** [benbenlaw/seaopolis#47]
Tinker's Construct: 
  Materials And You - Can be added to the Akashic Tome, but only if Tinker's Gadgetry isn't in the Akashic Tome.
  Puny Smelting - Cannot be added.
  Mighty Smelting - Cannot be added.
  Fantastic Foundry - Cannot be added.
  Tinker's Gadgetry - Can be added, but only if Materials and You isn't in the Akashic Tome.
Quark Mod:
   Ancient Tomes - Can be added, even though they don't actually contain any text and are just a way of improving enchanted books. Only one Ancient Tome can be added at a time. If the Akashic Tome is converted into an Ancient Tome and used to improve an enchanted book, all of the other books it contains are deleted.
Pedestal Mod:
  Enchantment Focused Books - Can be added - but only if the Pedestals book itself is not in the Akashic Tome. Can be enchanted while in the Tome, if used in an anvil the Tome is deleted as per how it works with Quark. 
Corail Tombstone Mod:
 Disenchantment Books - Can be added, following the rest of the theme here: if you actually use it while it's part of the Akashic Tome, all other books in the tome are deleted.
All other books from all other mods:
Seem to work just fine.

**Comment by AltonV** [comment]
I tried adding the mighty smelting to the config manually, but it still didn't work

**Comment by LotP1** [comment]
you can only add 1 book from each mod to the tome
