### ISSUE TITLE
Clouds in my base

### ISSUE THREAD

**Issue by julisana** [benbenlaw/seaopolis#52]
Just downloaded this mod pack through Curse tonight, so I assume I'm playing on the latest version. Clouds are floating their way through my base even though it spawns under water. They are typically visible on the lower level, where the trap door is, but are sometimes up high enough to be visible on the main level.

This isn't a critical bug, it's not impacting anything as far as I can tell. It was just odd and wanted to pass it along in case it was indicative of a larger situation.

**Comment by LotP1** [comment]
check your y level

**Comment by julisana** [comment]
The bottom of my base is at 129, I'm not sure where that is in relation to the ground on a non-modded Minecraft instance.

**Comment by LotP1** [comment]
it is exactly the same relation as in vanilla as it still uses vanilla's world engine

**Comment by julisana** [comment]
It's been a long time since I've actually played minecraft, that's why I said I didn't know where that was in relation to the ground on non-modded servers. I don't know if 129 is considered up in the sky, a middling level, or near the ground.

**Comment by SkullsInSuits** [comment]
In video settings, there is an option to turn off clouds. This is not a modpack bug, nor a bug at all, it is a vanilla feature and clouds will go through anything including water.
