### ISSUE TITLE
Enchanting tiered infusion crystal

### ISSUE THREAD

**Issue by happaes** [benbenlaw/seaopolis#56]
Hello,

I can't seem to enchant the tiered infusion crystals. According to JEI it should be possible 

![image](https://user-images.githubusercontent.com/63115635/119833089-1731a700-beff-11eb-8ce6-7270973cffa7.png)

When I put the crystal in an enchantment table, no available enchantments pop up.
When I tried the industrial foregoing enchantment factory, the factory accepted the infusion crystal but simply used up the essence and did not put an enchant on the crystal.

**Comment by DreamingLamb** [comment]
This may be intentional and probably best to check with the mod directly.  It can be enchanted using an Anvil, much like the Mystical Tools and armor.
