### ISSUE TITLE
Field projectors not working in the nether.

### ISSUE THREAD

**Issue by S4W1** [benbenlaw/seaopolis#57]
When i drop a item nothing happens. The first time i set them up they worked fine, it was 2 days ago and today it doesn't work. I managed to make it work once bcs it was a block and i just placed it and broke it, but in the recipe for the pedestal upgrade u have to use a ender pearl and it doesn't work.I even tried using a dropper.

**Comment by Crustaccean** [comment]
The way I have found to fix this is to break one of the field projectors and replace it.

If you've already placed down the multiblock recipe before replacing a projector, you'll have to break one of the blocks and replace it.
