### ISSUE TITLE
BetterDiving Oxygen Reserve

### ISSUE THREAD

**Issue by ColdDead** [benbenlaw/seaopolis#58]
https://github.com/Meldexun/BetterDiving/wiki/Oxygen
"The player's oxygen reserve automatically replenishes whenever they:

Come out of the water
Enter a powered vehicle" 

Oxygen not Refilling

**Comment by LotP1** [comment]
better diving oxygen mechanics were disabled because they messed with other mods

**Comment by ColdDead** [comment]
> better diving oxygen mechanics were disabled because they messed with other mods

:(
Thanks for this info
