### ISSUE TITLE
Self hosting a server

### ISSUE THREAD

**Issue by Consumerx54** [benbenlaw/seaopolis#59]
I have a server I just set up and would like to play with a few friends.  I guess with the default setup they all start in the same base.  Is there a command or something to set it up so that each player has his own base to start at?  I should mention I am self hosting this server.

**Comment by omglolbah** [comment]
./skyblock command has various tools for an operator to create teams and islands.

Enable players to make their own islands/teams when they join.
    edit config/skyblockbuilder/config.toml
    -> change "create-own-team = false" to true
    
    After that players can do "/skyblock create [teamname]" to make their island themselves if you prefer to let them.

**Comment by Consumerx54** [comment]
Thanks for the info but I still can't get it to work.  after they type /skyblock it will not accept create as a command.  This mod pack is very interesting and everyone is anxious to play so any help is appreciated.. TY

**Comment by benbenlaw** [comment]
join the discord load of people there might be able to help
