### ISSUE TITLE
Can't pin quests, which in progess, only done

### ISSUE THREAD

**Issue by Netlighter** [benbenlaw/seaopolis#61]
![image](https://user-images.githubusercontent.com/19776413/120064274-07879f00-c074-11eb-8e0c-58cdb841cf47.png)
is there a bug or just a strange config?

**Comment by LotP1** [comment]
this is a mod issue, go report it to ftb quests

**Comment by Vikbor5342** [comment]
You can report it here https://github.com/FTBTeam/FTB-Quests/issues but before you do check https://github.com/FTBTeam/FTB-Quests/projects/1 if it is planed and known.
