### ISSUE TITLE
Quest book not updating

### ISSUE THREAD

**Issue by imeight1** [benbenlaw/seaopolis#62]
I have multiple quests that I have the items for and they will not complete no matter what I do.

**Comment by LotP1** [comment]
make sure you've completed all the dependencies

**Comment by WikiRik** [comment]
From the Discord;

Quest not completing? Make sure you have completed the dependencies by clicking the little arrow on the left on the quest window.
![dependencies.png](https://user-images.githubusercontent.com/13023439/120178931-4c453e80-c20a-11eb-9ec0-5ab5f7ba2501.png)

**Comment by imeight1** [comment]
Thank you that was exactly my issue
