### ISSUE TITLE
Multiple Versions of Silver Ingots

### ISSUE THREAD

**Issue by BigMikJ** [benbenlaw/seaopolis#67]
Smelting silver ore chunks in a smelter produces "Better Diving" version of the ingot. Can form into blocks and place in Storage drawers. Once you de-compact the block, the ingots are now shown as "Thermal Series" ingots and cannot be be placed back in the same drawer as the "Better Diving" ingots.

**Comment by benbenlaw** [comment]
what version?

**Comment by BigMikJ** [comment]
- [ ] Running client and server version B5.3

**Comment by benbenlaw** [comment]
update

**Comment by BigMikJ** [comment]
That resolved it, Thanks!

**Comment by Sunlis** [comment]
This seems to be an issue again in R1.5. Ingots output by smeltery are "Better Diving". Bringing them into the player's inventory immediately converts them to "Thermal Series".
