### ISSUE TITLE
Tinkers smeltery/refined storage crafter

### ISSUE THREAD

**Issue by GrilliOG** [benbenlaw/seaopolis#69]
crafters are not responding to requests, no pattern works the crafter will not pull the items from my network

**Comment by carmen2304** [comment]
I have the exact same problem! Tried both normal and gold crafter, and tested in a tinkers smeltery set up as well as directly attached to my network but neither worked.

**Comment by vardash** [comment]
Try to place the big black opening from the Chute towards inward the Smelterty. I just found it out

**Comment by benbenlaw** [comment]
use a buffer chest
