### ISSUE TITLE
World

### ISSUE THREAD

**Issue by drachentrix** [benbenlaw/seaopolis#70]
When I try to go into my world the game is normal but then nothing stands and I'm just seeing a freezed screen and nothing happens

**Comment by drachentrix** [comment]
OTHER worlds work but not my main and I don't know why

**Comment by drachentrix** [comment]
and now my World not exist not more my whole playtime down like I was so far

**Comment by drachentrix** [comment]
or i think it's back cause backup but I need to look what backup it is

**Comment by drachentrix** [comment]
I think its the right but I can't enter the world

**Comment by drachentrix** [comment]
I hope I can get back my stuff or I will delete this pack 
cause this grind again nah thank you

**Comment by Vikbor5342** [comment]
Please join the discord for help about this. https://discord.gg/aKgDH99hBu
