### ISSUE TITLE
Kill Naga Quest Not Updating for Seabucks.

### ISSUE THREAD

**Issue by icyred64** [benbenlaw/seaopolis#71]
I Have killed the Naga twice. I have the requirement blank magic map and questing ram trophy complete. Only thing light up is "Kill: 1X Naga" Which I have done twice. I have dropped the scales and trophy and tried picking up just the trophy then the scales and vice versa and still wont say I killed the Naga. I checked "Advancements" and shows that I have 2/2 for NAGA "Time to even the scales" so it has recorded that I did the Naga but the Seabucks Quest Book has not.

**Comment by Vikbor5342** [comment]
Did you kill the naga by shooting it or punching it?

**Comment by icyred64** [comment]
Ah I think I know where youre going with this. I shot it. Let me try shooting it till its almost dead then sword it. brb

**Comment by icyred64** [comment]
Thank you. That solved it.
