### ISSUE TITLE
Ur-Ghast

### ISSUE THREAD

**Issue by Dudemen** [benbenlaw/seaopolis#74]
Killed Ur-Ghast in twilight forest gotten 
![ee](https://user-images.githubusercontent.com/85650389/121435330-98b11c80-c976-11eb-802d-0e5850505b73.png)
![e](https://user-images.githubusercontent.com/85650389/121435336-9b137680-c976-11eb-8de6-d7538b693837.png)

achievement for killing it however the quest did not update

**Comment by LotP1** [comment]
unless you're in QTA1 you need to kill it with melee (you might need melee in QTA1 too, but i don't remember)
