### ISSUE TITLE
Crafting Lingering Potion of Harming (II) in Potion Brewer crashes server

### ISSUE THREAD

**Issue by travveh** [benbenlaw/seaopolis#77]
Crafting a Lingering Potion of Harming (II) in the potion brewer crashes the server at essentially the same tick as the final operation of the brewer happens and it passes to the output inventory. Server will not relaunch (restored from backup fine). Verified in single player creative world, full client crash, can't get back in. 
Simply possessing the potion is fine.
Crafted one just fine in a vanilla brewing stand in a single player creative world as well.

Initial server crash:
[crash-2021-06-11_06.54.03-server.txt](https://github.com/benbenlaw/seaopolis/files/6638074/crash-2021-06-11_06.54.03-server.txt)

**Comment by LotP1** [comment]
this is a problem with Industrial Foregoing
