### ISSUE TITLE
Furnace bug

### ISSUE THREAD

**Issue by BrycethePsycho** [benbenlaw/seaopolis#8]
After crafting a furnace and setting it down, I appear unable to open the inventory of said furnace.

**Comment by benbenlaw** [comment]
does restarting fix this?

**Comment by BrycethePsycho** [comment]
It does not, that was the first thing I tried

**Comment by benbenlaw** [comment]
claimed chunks?

**Comment by BrycethePsycho** [comment]
It fixed itself after a second restart
