### ISSUE TITLE
mystical agriculture seed problems

### ISSUE THREAD

**Issue by GrilliOG** [benbenlaw/seaopolis#82]
some of my seeds are just disappearing after being harvested by plant gatherer, i cant find them anywhere i have to keep remaking them please help

**Comment by Zaseru** [comment]
Having the same issue. Seeds should be auto exported from my refined system into a sower to then be harvested by a gatherer but certain seeds seem to either not drop or dissapear somewhere in the line. (Having issues with creeper and obsidian seeds myself)
