### ISSUE TITLE
Kill Ender Dragon quest doesn't fulfill

### ISSUE THREAD

**Issue by Basuro** [benbenlaw/seaopolis#83]
I just killed the Ender Dragon for the second time (first time I failed to check in the "Enter End" quest before...), and after killing the dragon I cannot hand in the "Kill Ender Dragon" quest.

**Comment by Vikbor5342** [comment]
What version are you on?

**Comment by LotP1** [comment]
in pre QTA versions quests don't register ranged kills
any version from QTA 1 and forward will not have this problem

**Comment by Basuro** [comment]
I'm currently on 5.5, as suggested by Curseforge Launcher 

Am 15. Juni 2021 23:53:42 MESZ schrieb Vikbor5342 ***@***.***>:

**Comment by Basuro** [comment]
What is QTA? I'm on V5.5, according to Curseforge.. 

Am 16. Juni 2021 00:06:45 MESZ schrieb LotP1 ***@***.***>:

**Comment by LotP1** [comment]
QTA are Quest Test Alpha versions
it's a few beta releases (which is probably why you don't see them) that Ben has released to test the new quest features before they become part of the full Beta releases.
i would suggest joining the discord for more information on how to update and what the changes are.

**Comment by benbenlaw** [comment]
fixed in 3.0
