### ISSUE TITLE
Pipezmod -> Tinkers Construct Drain / Chute connect problem

### ISSUE THREAD

**Issue by vardash** [benbenlaw/seaopolis#88]
Server Version: 5.5
Client Version 5.5
Worldcreation 5.2

The Pipezmod have issues to connect properly to the Drain or Chute from Tinkers Constukt. Sometimes it only works after several attempts

**Comment by LotP1** [comment]
this is not a problem with Seaopolis, go report it to pipez or tinkers
a quick fix is to break and replace the pipe and drain/chute
