### ISSUE TITLE
ftbquests not traveling over

### ISSUE THREAD

**Issue by cono6783** [benbenlaw/seaopolis#92]
when ever I updated the pack on curseforge I made it go a new profile and transferred the save data over.  I logged in to the world and when i opened ftbquests none of them were completed and it won't let me complete any of them.
Is ftbquests progress saved somewhere other than saves?

I expected to have the same progress on my quests

I clicked the check and it did not accept
https://user-images.githubusercontent.com/86134894/122775701-05c68b00-d270-11eb-9a5a-75a3b4730b94.mp4

I updated from B5.5 to 1.1

the same thing happened when i tried to move the save data from curseforge to a different launcher

**Comment by benbenlaw** [comment]
this is not a bug this is becuase ftb quests changed the way quests were saved
