### ISSUE TITLE
Can't access commad/chat - Singleplayer

### ISSUE THREAD

**Issue by Radagast** [benbenlaw/seaopolis#97]
**Describe the bug**
Unable to open the chat window - Java/Linux/Singleplayer

**To Reproduce**
1. Create world with cheats enabled
2. Enter world and press ```/``` 
3. Nothing happens.
4. Tried the ```Open to Lan/Enable Cheats``` same result
5. Checked Key Mappings 

**Expected behavior**
Console/ Chat window should open

**Screenshots**
N/A

**Version**
Java 1.8.0_291 / Seaopolis 1.3 / Forge forge-1.16.5-36.1.16

**Additional context**
I also noticed the weather and game mode icons to top left also don't work.

```config/sidebar_buttons.json```

```
{
	"ftbteams": {
		"my_team": true
	},
	"ftbquests": {
		"quests": true
	},
	"ftblibrary": {
		"toggle.gamemode": true,
		"toggle.rain": true,
		"toggle.day": true,
		"toggle.night": true
	},
	"ftbchunks": {
		"chunks": true
	}
}
```

Other Modpacks seem to work correctly

**Comment by Radagast** [comment]
I appreciate this is still open but I just wanted to mention I updated to 1.5. I also noticed F3+F4 doesn't work either.

**Comment by Vikbor5342** [comment]
Could you send logs?

**Comment by Radagast** [comment]
New update. I was reading through ```Options.txt``` and noticed some odd settings such as ```chatVisibility:2```. I decided to delete the file and let it be recreated. Now everything seems to work. No idea how that got changed as I don't use chat on singleplayer.
